name: CI-minikube
on: 
  push:
    branches: [main]
jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      env:
        mode: minikube
      run: |
        set -x
        compose=etc/docker/$mode/$(basename $GITHUB_REPOSITORY).yaml
        date=$(date +%s)
        test -d run && sudo cp -rv run/* /run
        sed -i s/image.*$/image:' '$mode:$date/ $compose
        docker build -t $mode:$date --no-cache .
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        sudo dpkg -i minikube_latest_amd64.deb
        minikube start
        minikube kubectl -- apply -f $compose
        while true
          do
            sleep 1
            minikube kubectl -- get deploy
            minikube kubectl -- get deploy | grep '\([0-9]\)/\1' && break
          done
        

      
